/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_api_v1_admin_users__uid__patch"];
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness plus the provenance a client needs to label what it is showing. Reports
         *     the serving snapshot's version, so a deployment can confirm it reads the lake.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_v1_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/watchlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Watchlists */
        get: operations["list_watchlists_api_v1_me_watchlists_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/watchlists/{watchlist_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Watchlist
         * @description Create or replace a watchlist. Every security must exist in the served snapshot.
         */
        put: operations["put_watchlist_api_v1_me_watchlists__watchlist_id__put"];
        post?: never;
        /** Delete Watchlist */
        delete: operations["delete_watchlist_api_v1_me_watchlists__watchlist_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/refresh/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Daily
         * @description Start the production refresh. Admins only. Returns at once with the run id: the
         *     refresh runs in GitHub Actions, and ``GET /jobs/{run_id}`` follows it.
         */
        post: operations["refresh_daily_api_v1_refresh_daily_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/securities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Search current and past symbols, ISINs and names.
         */
        get: operations["search_api_v1_securities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/securities/{security_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail */
        get: operations["detail_api_v1_securities__security_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/securities/{security_id}/data-quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data Quality */
        get: operations["data_quality_api_v1_securities__security_id__data_quality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/securities/{security_id}/weekly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Weekly
         * @description Stored weekly bars as of the data's ``as_of``. ``segments=valid`` (default) returns
         *     only the continuity segment analysis may use; ``all`` returns every segment (charts).
         */
        get: operations["weekly_api_v1_securities__security_id__weekly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Operations Status */
        get: operations["operations_status_api_v1_system_operations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Snapshots
         * @description Published snapshot history, newest first. The API still serves only what the
         *     pointer names; this is a record of publications, never a way to choose one.
         */
        get: operations["list_snapshots_api_v1_system_snapshots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Serving Status */
        get: operations["serving_status_api_v1_system_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ComponentVersions */
        ComponentVersions: {
            /** Api */
            api: string;
            /** Core */
            core: string;
            /** Engine */
            engine: string;
            /** Pipeline */
            pipeline: string;
        };
        /** DataQualityResponse */
        DataQualityResponse: {
            /** Continuity Breaks */
            continuity_breaks: number;
            /**
             * Data As Of
             * Format: date
             */
            data_as_of: string;
            /** Dq Version */
            dq_version: string;
            /** Failures */
            failures: number;
            /** Findings */
            findings: components["schemas"]["Finding"][];
            /** Meta Version */
            meta_version: string;
            /** Security Id */
            security_id: string;
            /** Status */
            status: string;
            /** Usable From */
            usable_from: string | null;
            /** Warnings */
            warnings: number;
        };
        /**
         * Environment
         * @enum {string}
         */
        Environment: "local" | "ci" | "prod";
        /** Finding */
        Finding: {
            /** Breaks Continuity */
            breaks_continuity: boolean;
            /** Code */
            code: string;
            /** Detail */
            detail: string;
            /** Dimension */
            dimension: string;
            /** End Date */
            end_date: string | null;
            /** Evidence */
            evidence: string;
            /** Severity */
            severity: string;
            /** Start Date */
            start_date: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            environment: components["schemas"]["Environment"];
            /** Exchange */
            exchange: string;
            /** Methodology Hash */
            methodology_hash: string;
            /**
             * Server Time
             * Format: date-time
             */
            server_time: string;
            serving: components["schemas"]["ServingInfo"] | null;
            /**
             * Status
             * @constant
             */
            status: "ok";
            versions: components["schemas"]["ComponentVersions"];
        };
        /** Identifier */
        Identifier: {
            /** Identifier Type */
            identifier_type: string;
            /** Identifier Value */
            identifier_value: string;
            /**
             * Valid From
             * Format: date
             */
            valid_from: string;
            /**
             * Valid To
             * Format: date
             */
            valid_to: string;
        };
        /** OperationsStatus */
        OperationsStatus: {
            active_run: components["schemas"]["RunView"] | null;
            /** Api Status */
            api_status: string;
            /** Api Version */
            api_version: string;
            /** Can Refresh */
            can_refresh: boolean;
            last_run: components["schemas"]["RunView"] | null;
            last_successful_run: components["schemas"]["RunView"] | null;
            /** Refresh Configured */
            refresh_configured: boolean;
            serving: components["schemas"]["ServingView"] | null;
        };
        /** RefreshAccepted */
        RefreshAccepted: {
            /** Run Id */
            run_id: string;
            status: components["schemas"]["RunStatus"];
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "QUEUED" | "RUNNING" | "SUCCEEDED" | "FAILED" | "CANCELLED";
        /** RunView */
        RunView: {
            /** Completed At */
            completed_at: string | null;
            current_stage: components["schemas"]["Stage"] | null;
            /** Data As Of */
            data_as_of: string | null;
            /** Duration Seconds */
            duration_seconds: number | null;
            /** Error Summary */
            error_summary: string | null;
            /** Github Run Id */
            github_run_id: string | null;
            /** Github Run Url */
            github_run_url: string | null;
            /** Job Type */
            job_type: string;
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
            /** Requested By */
            requested_by: string;
            /** Run Id */
            run_id: string;
            /** Serving Version */
            serving_version: string | null;
            snapshot_outcome: components["schemas"]["SnapshotOutcome"] | null;
            /** Stages */
            stages: components["schemas"]["StageRecord"][];
            /** Started At */
            started_at: string | null;
            status: components["schemas"]["RunStatus"];
            /** Trigger */
            trigger: string;
            /** Weekly Version */
            weekly_version: string | null;
        };
        /** RunsPage */
        RunsPage: {
            /** Next Before */
            next_before: string | null;
            /** Runs */
            runs: components["schemas"]["RunView"][];
        };
        /** SearchResponse */
        SearchResponse: {
            /**
             * Data As Of
             * Format: date
             */
            data_as_of: string;
            /** Meta Version */
            meta_version: string;
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["SecuritySummary"][];
        };
        /** SecurityDetail */
        SecurityDetail: {
            /** Analytical Universe */
            analytical_universe: boolean;
            /** Continuity Breaks */
            continuity_breaks: number;
            /** Current Segment Id */
            current_segment_id: string;
            /**
             * Data As Of
             * Format: date
             */
            data_as_of: string;
            /** Failures */
            failures: number;
            /**
             * First Date
             * Format: date
             */
            first_date: string;
            /** Identifiers */
            identifiers: components["schemas"]["Identifier"][];
            /** Instrument Type */
            instrument_type: string;
            /** Isin */
            isin: string | null;
            /**
             * Last Date
             * Format: date
             */
            last_date: string;
            /** Listing Status */
            listing_status: string;
            /** Meta Version */
            meta_version: string;
            /** Name */
            name: string | null;
            /** Security Id */
            security_id: string;
            /** Segments */
            segments: components["schemas"]["Segment"][];
            /** Series */
            series: string | null;
            /** Sessions */
            sessions: number;
            /** Status */
            status: string;
            /** Symbol */
            symbol: string | null;
            /** Usable From */
            usable_from: string | null;
            /** Usable Sessions */
            usable_sessions: number;
            /** Warnings */
            warnings: number;
        };
        /** SecuritySummary */
        SecuritySummary: {
            /** Analytical Universe */
            analytical_universe: boolean;
            /** Instrument Type */
            instrument_type: string;
            /** Isin */
            isin: string | null;
            /**
             * Last Date
             * Format: date
             */
            last_date: string;
            /** Listing Status */
            listing_status: string;
            /** Name */
            name: string | null;
            /** Security Id */
            security_id: string;
            /** Series */
            series: string | null;
            /** Status */
            status: string;
            /** Symbol */
            symbol: string | null;
            /** Usable From */
            usable_from: string | null;
        };
        /** Segment */
        Segment: {
            /** Cause */
            cause: string;
            /** Continuity Segment Id */
            continuity_segment_id: string;
            /**
             * Segment End
             * Format: date
             */
            segment_end: string;
            /**
             * Segment Start
             * Format: date
             */
            segment_start: string;
            /** Sessions */
            sessions: number;
        };
        /**
         * ServingInfo
         * @description Which lake snapshot this instance serves. Versions only: no market data.
         */
        ServingInfo: {
            /**
             * Data As Of
             * Format: date
             */
            data_as_of: string;
            /** Meta Version */
            meta_version: string;
        };
        /** ServingStatus */
        ServingStatus: {
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /**
             * Data As Of
             * Format: date
             */
            data_as_of: string;
            /** Exchange */
            exchange: string;
            /** Meta Version */
            meta_version: string;
            /** Refresh Seconds */
            refresh_seconds: number;
            /**
             * Snapshot Generated At
             * Format: date-time
             */
            snapshot_generated_at: string;
            /** Snapshot Loaded At */
            snapshot_loaded_at: string | null;
            /** Versions */
            versions: {
                [key: string]: string;
            };
        };
        /** ServingView */
        ServingView: {
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /**
             * Data As Of
             * Format: date
             */
            data_as_of: string;
            /** Meta Version */
            meta_version: string;
            /**
             * Snapshot Generated At
             * Format: date-time
             */
            snapshot_generated_at: string;
            /** Versions */
            versions: {
                [key: string]: string;
            };
        };
        /**
         * SnapshotOutcome
         * @enum {string}
         */
        SnapshotOutcome: "PUBLISHED" | "UNCHANGED" | "NOT_PUBLISHED";
        /** SnapshotView */
        SnapshotView: {
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /**
             * Data As Of
             * Format: date
             */
            data_as_of: string;
            /** Live */
            live: boolean;
            /** Published At */
            published_at: string | null;
            /** Run Id */
            run_id: string | null;
            /** Schema Version */
            schema_version: number;
            /** Snapshot Id */
            snapshot_id: string;
            /**
             * Staged At
             * Format: date-time
             */
            staged_at: string;
            /** Status */
            status: string;
            /** Versions */
            versions: {
                [key: string]: string;
            };
        };
        /**
         * Stage
         * @enum {string}
         */
        Stage: "INGEST" | "CORPORATE_ACTIONS" | "ADJUSTMENT" | "DATA_QUALITY" | "WEEKLY" | "PUBLISH_SERVING";
        /** StageRecord */
        StageRecord: {
            /** Completed At */
            completed_at?: string | null;
            /** Details */
            details?: {
                [key: string]: string | number | boolean | null;
            };
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Error Summary */
            error_summary?: string | null;
            /** Records Processed */
            records_processed?: number | null;
            stage: components["schemas"]["Stage"];
            /** Started At */
            started_at?: string | null;
            /** @default QUEUED */
            status: components["schemas"]["RunStatus"];
            /** Version */
            version?: string | null;
        };
        /** User */
        User: {
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Email */
            email?: string | null;
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /**
             * Role
             * @default user
             * @enum {string}
             */
            role: "admin" | "user";
            /** Uid */
            uid: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
        };
        /** UserPatch */
        UserPatch: {
            /** Enabled */
            enabled?: boolean | null;
            /** Role */
            role?: ("admin" | "user") | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Watchlist */
        Watchlist: {
            /** Name */
            name: string;
            /** Security Ids */
            security_ids: string[];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
            /** Watchlist Id */
            watchlist_id: string;
        };
        /** WatchlistIn */
        WatchlistIn: {
            /** Name */
            name: string;
            /** Security Ids */
            security_ids: string[];
        };
        /** WeeklyBarOut */
        WeeklyBarOut: {
            /** Close */
            close: string;
            /** Closes On Special Session */
            closes_on_special_session: boolean;
            /** Closing Session Type */
            closing_session_type: string | null;
            /** Continuity Segment Id */
            continuity_segment_id: string;
            /**
             * First Session Date
             * Format: date
             */
            first_session_date: string;
            /** High */
            high: string;
            /** Is Complete */
            is_complete: boolean;
            /** Iso Week */
            iso_week: number;
            /** Iso Year */
            iso_year: number;
            /**
             * Last Session Date
             * Format: date
             */
            last_session_date: string;
            /** Low */
            low: string;
            /** Open */
            open: string;
            /** Partial Reason */
            partial_reason: string | null;
            /** Raw Close */
            raw_close: string;
            /** Special Sessions */
            special_sessions: number;
            /** Trading Days */
            trading_days: number;
            /** Volume */
            volume: string;
            /**
             * Week End Date
             * Format: date
             */
            week_end_date: string;
            /**
             * Week Start Date
             * Format: date
             */
            week_start_date: string;
        };
        /** WeeklyResponse */
        WeeklyResponse: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Bars */
            bars: components["schemas"]["WeeklyBarOut"][];
            /** Current Segment Id */
            current_segment_id: string;
            /** Meta Version */
            meta_version: string;
            /** Security Id */
            security_id: string;
            /** Segment Ids */
            segment_ids: string[];
            /**
             * Segments
             * @enum {string}
             */
            segments: "valid" | "all";
            /** Versions */
            versions: {
                [key: string]: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_users_api_v1_admin_users_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_v1_admin_users__uid__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_jobs_api_v1_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
                /** @description requested_at cursor */
                before?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__run_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_watchlists_api_v1_me_watchlists_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Watchlist"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_watchlist_api_v1_me_watchlists__watchlist_id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                watchlist_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Watchlist"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_watchlist_api_v1_me_watchlists__watchlist_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                watchlist_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_daily_api_v1_refresh_daily_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshAccepted"];
                };
            };
            /** @description A refresh is already active */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_securities_get: {
        parameters: {
            query: {
                /** @description Symbol, ISIN or name */
                q: string;
                universe?: "analytical" | "all";
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detail_api_v1_securities__security_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                security_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecurityDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    data_quality_api_v1_securities__security_id__data_quality_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                security_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataQualityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    weekly_api_v1_securities__security_id__weekly_get: {
        parameters: {
            query?: {
                segments?: "valid" | "all";
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                security_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    operations_status_api_v1_system_operations_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationsStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_snapshots_api_v1_system_snapshots_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    serving_status_api_v1_system_status_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServingStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
